<?php
/** @var array $credentials форма логина */
/** @var string $error сообщение при логине */
?><!doctype html>
<html lang="ru">
<?= template_render('_elements/head', ['heading' => 'Login']); ?>
<body>
<?= template_render('_elements/header'); ?>

<main>
    <div class="container">
        <div class="row center form-container">
            <h2>Админка</h2>
            <!-- TODO -->
        </div>
    </div>
</main>

<?= template_render('_elements/footer'); ?>
</body>
</html>