<?php
/** @var array $credentials форма логина */
/** @var string $error сообщение при логине */
?><!doctype html>
<html lang="ru">
<?= template_render('_elements/head', ['heading' => 'Login']); ?>
<body>
<?= template_render('_elements/header'); ?>

<main>
    <div class="container">
        <div class="row center form-container">
            <form action="<?= _e(router_get_path('login')) ?>" method="post" id="login-form"
                  class="col s12 m8 offset-m2 l6 offset-l3 card hoverable login-form">
                <div class="form-inner">
                    <h3>Войти</h3>

                    <div class="row row-login-error">
                        <div class="col s12 red-text" data-login-error="login-error"><?= _e($error) ?></div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <input id="username" name="username" type="text"
                                   value="<?= _e($credentials['username']) ?>"
                                   maxlength="255"
                                   required>
                            <label for="username">Имя пользователя</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <input id="password" name="password" type="password"
                                   value="<?= _e($credentials['password']) ?>"
                                   required>
                            <label for="password">Пароль</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <button type="submit"
                                    class="col s12 waves-effect waves-light btn-large deep-orange darken-4">
                                Войти
                            </button>
                        </div>
                    </div>

                    <div class="row row-progress-bottom">
                        <div class="col s12 progress-container" data-progress="progress">
                            <div class="progress deep-orange lighten-4">
                                <div class="indeterminate deep-orange darken-4"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>

<?= template_render('_elements/footer'); ?>
</body>
</html>