<footer class="page-footer grey darken-3">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">О нас</h5>

                <p class="grey-text text-lighten-4">Мы — команда профессионалов в своей сфере. Наши цели —
                    довольные заказчики и богатые исполнители. Мы никогда не останавливаемся на достигнутом
                    и всегда готовы помочь любому, кто готов заложить свою душу.
                </p>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Помощь</h5>
                <ul>
                    <li><a class="white-text" href="http://php.net/support.php"
                           title="Справка по PHP" target="_blank">PHP</a></li>
                    <li><a class="white-text" href="https://docs.npmjs.com/cli/help" target="_blank"
                           title="Помощь по NPM">NPM</a></li>
                    <li><a class="white-text" href="https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md"
                           target="_blank" title="Руководство Gulp">Gulp</a></li>
                    <li><a class="white-text" href="http://materializecss.com/" target="_blank"
                           title="Materialize CSS">Materialize</a>
                    </li>
                </ul>
            </div>
            <div class="col l3 s12 contacts">
                <h5 class="white-text">Контакты</h5>
                <ul>
                    <li><!--suppress SpellCheckingInspection -->
                        <a class="white-text" href="tel:+02890180666"
                           title="Конспиролог перепутал евразийца с атлантистом,&#010сплюнул и прочистил дуло - ах же, суки, как похожи -&#010с точки зренья диалектик - три девятки, три шестерки,&#010если любишь сладко кушать, вообщем то одно и то же">
                            <i class="material-icons mdi-communication-phone"></i> (028) 9018 0666</a></li>
                    <li><a class="white-text" href="mailto:mef@self.test" title="Напишите нам">
                            <i class="material-icons mdi-communication-email"></i> mef@self.test</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            &copy; 2015 Ilya Pleshakov &bullet;
            <a class="deep-orange-text text-lighten-3" href="http://da-eto.info" target="_blank">da-eto</a>
        </div>
    </div>
</footer>


<script src="https://yastatic.net/jquery/2.1.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/static/vendor/jquery-2.1.4/jquery.min.js"><\/script>');</script>
<script src="/static/js/lib.min.js?1608211951"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/livestamp/1.1.2/livestamp.min.js"></script>
<script>window.jQuery().livestamp || document.write('<script src="/static/vendor/livestamp-1.1.2/livestamp.min.js"><\/script>');</script>
<script src="/static/js/main.min.js?1608211951"></script>

<?= template_render('_elements/ga'); ?>
