<?php
$user = auth_get_current_user();
?>
<header>
    <nav class="deep-orange darken-4" role="navigation">
        <div class="nav-wrapper container">
            <a href="/" title="На главную" class="brand-logo">
                <img src="/static/img/logo.png" alt="MF">
            </a>

            <?php if ($user) : ?>

                <ul class="right hide-on-med-and-down">
                    <li>
                        <form action="<?= _e(router_get_path('logout')) ?>" method="post">
                            <button type="submit" class="btn-flat nav-logout" title="Выйти из системы">
                                <i class="material-icons mdi-action-perm-identity left"></i>Выйти
                            </button>
                        </form>
                    </li>

                    <?php if ($user['avatar']): ?>

                        <li>
                            <img src="<?= _e($user['avatar']) ?>"
                                 alt="<?= _e($user['username']) ?>" title="<?= _e($user['username']) ?>"
                                 class="circle nav-avatar">
                        </li>

                    <?php else : ?>

                        <li>
                            <span title="<?= _e($user['username']) ?>">(<?= _e($user['username']) ?>)</span>
                        </li>

                    <?php endif; ?>
                </ul>
                <ul class="right">
                    <li>
                        <div class="nav-balance">
                            <i class="material-icons mdi-editor-attach-money left"></i>
                            <?= _e(_money($user['balance'])) ?>
                        </div>
                    </li>
                </ul>

                <ul id="nav-mobile" class="side-nav">
                    <li>
                        <form action="<?= _e(router_get_path('logout')) ?>" method="post">
                            <button type="submit" class="btn-flat nav-logout" title="Выйти из системы">
                                <i class="material-icons mdi-action-perm-identity left"></i>Выйти
                            </button>
                        </form>
                    </li>
                </ul>

            <?php else : ?>

                <ul class="right hide-on-med-and-down">
                    <li>
                        <a href="<?= _e(router_get_path('login')) ?>" title="Войти в систему"><i
                                class="material-icons mdi-action-perm-identity left"></i>Вход</a>
                    </li>
                </ul>

                <ul id="nav-mobile" class="side-nav">
                    <li>
                        <a href="<?= _e(router_get_path('login')) ?>" title="Войти в систему"><i
                                class="material-icons mdi-action-perm-identity left"></i>Вход</a>
                    </li>
                </ul>

            <?php endif; ?>

            <a href="javascript:" title="Меню" data-activates="nav-mobile" class="button-collapse"><i
                    class="material-icons mdi-navigation-menu"></i></a>
        </div>
    </nav>
</header>
