<?php
/** @var string $heading заголовок страницы в title */
?>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
    <title><?= $heading ? _e($heading) . ' — ' : ''; ?>Mephistos</title>

    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="/static/css/main.min.css?1608211951" type="text/css" rel="stylesheet" media="screen,projection">

    <link rel="apple-touch-icon" href="/apple-touch-icon-114.png" sizes="57x57">
    <link rel="apple-touch-icon" href="/apple-touch-icon-114.png" sizes="114x114">
    <link rel="apple-touch-icon" href="/apple-touch-icon-144.png" sizes="72x72">
    <link rel="apple-touch-icon" href="/apple-touch-icon-144.png" sizes="144x144">
    <link rel="shortcut icon" href="/favicon.ico?1608131617">
    <?= template_render('_elements/ga'); ?>
</head>
