<?php
/** @var array $order ['price' => цена, 'description' => описание] */
/** @var array $errors ['price'? => array, 'description'? => array] */
/** @var array $createdOrder */
/** @var array $createErrors */
?><!doctype html>
<html lang="ru">
<?= template_render('_elements/head', ['heading' => 'Добавить заказ']); ?>
<body>
<?= template_render('_elements/header'); ?>

<main>
    <div class="container">
        <div class="row center form-container">
            <form action="<?= _e(router_get_path('orders', 'create')) ?>" method="post"
                  id="order-form"
                  class="col s12 m10 offset-m1 card hoverable order-form">
                <?= _csrf_hidden(['orders', 'create']) ?>
                <div class="form-inner">
                    <h3>Добавить заказ</h3>

                    <?php if (!empty($createErrors)) : ?>
                        <?= template_render('_elements/error_row', ['errors' => $createErrors]) ?>
                    <?php endif; ?>

                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix mdi-editor-attach-money"></i>
                            <input id="price" name="price"
                                   value="<?= _e($order['price']) ?>"
                                   type="number" min="1" max="10000" step="0.01"
                                   class=""
                                   required>

                            <?= template_render('_elements/errors_label', [
                                'for' => 'price',
                                'errors' => !empty($errors['price']) ? $errors['price'] : [],
                            ]) ?>

                            <label for="price">Стоимость</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix mdi-editor-insert-comment"></i>
                            <textarea id="description" name="description"
                                      class="materialize-textarea"
                                      maxlength="665"
                                      required><?= _e($order['description']) ?></textarea>

                            <?= template_render('_elements/errors_label', [
                                'for' => 'description',
                                'errors' => !empty($errors['description']) ? $errors['description'] : [],
                            ]) ?>

                            <label for="description">Описание</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <button type="submit"
                                    class="col s12 waves-effect waves-light btn-large deep-orange darken-4">
                                Добавить
                            </button>
                        </div>
                    </div>

                    <div class="row row-progress-bottom">
                        <div class="col s12 progress-container" data-progress="progress">
                            <div class="progress deep-orange lighten-4">
                                <div class="indeterminate deep-orange darken-4"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <?php if (!empty($createdOrder)) : ?>
            <div class="row center">
                <h4 class="col s12">Заказ добавлен</h4>
            </div>
        <?php endif; ?>
    </div>


    <div class="container">
        <div class="row">
            <div class="col s12">
                <ul class="collection order-list order-list-created" id="created-orders">
                </ul>

                <script type="text/x-handlebars-template" id="created-orders-new">
                    <li class="collection-item avatar order-item animated bounce">
                        {{#if customer.avatar}}
                            <img src="{{customer.avatar}}" alt="{{customer.username}}" class="circle">
                            <span class="title">{{customer.username}} &bullet;
                                <span class="deep-orange-text">{{order.price_dollar}}</span>
                                <nobr>&bullet;
                                    <span class="blue-grey-text text-lighten-2">{{order.created}}</span>
                                </nobr>
                            </span>
                        {{else}}
                            <span class="title">
                                <span class="deep-orange-text">{{order.price_dollar}}</span>
                                <nobr>&bullet;
                                    <span class="blue-grey-text text-lighten-2">{{order.created}}</span>
                                </nobr>
                            </span>
                        {{/if}}
                        <p>{{order.description}}</p>
                    </li>
                </script>
            </div>
        </div>
    </div>
</main>

<?= template_render('_elements/footer'); ?>
</body>
</html>