<?php
?><!doctype html>
<html lang="ru">
<?= template_render('_elements/head', ['heading' => 'Добавить заказ']); ?>
<body>
<?= template_render('_elements/header'); ?>

<main>
    <div class="container">
        <div class="row center form-container">
            <form class="col s12 m10 offset-m1 card hoverable order-form">
                <div class="form-inner">

                    <h3>Добавить заказ</h3>

                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix mdi-editor-attach-money"></i>
                            <input id="price" name="price" type="number" min="1" max="10000" step="0.01"
                                   class="validate" required>
                            <label for="price"
                                   data-error="Введите сумму от 1 до 10000 с точностью до центов">Стоимость</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix mdi-editor-insert-comment"></i>
                            <textarea id="description" name="description" class="materialize-textarea validate"
                                      required maxlength="665"></textarea>
                            <label for="description">Описание</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <button type="submit"
                                    class="col s12 waves-effect waves-light btn-large deep-orange darken-4">
                                Добавить
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>

<?= template_render('_elements/footer'); ?>
</body>
</html>