<?php
/** @var array $orders */
/** @var array $customers */
?><!doctype html>
<html lang="ru">
<?= template_render('_elements/head', ['heading' => 'Список заказов']); ?>
<body>
<?= template_render('_elements/header'); ?>

<main>
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h2>Заказы</h2>

                <?php if (!empty($orders)) : ?>

                    <ul class="collection order-list">
                        <?php foreach ($orders as $order) : ?>
                            <?php
                            $customer = isset($customers[$order['customer_id']]) ?
                                $customers[$order['customer_id']] :
                                false;
                            ?>
                            <li class="collection-item avatar order-item" id="order-item-<?= _e($order['id']) ?>">

                                <?php if (!empty($customer['avatar']) && isset($customer['username'])) : ?>
                                    <img src="<?= _e($customer['avatar']) ?>"
                                         alt="<?= _e($customer['username']) ?>"
                                         class="circle">

                                    <span class="title">
                                        <?= _e($customer['username']) ?>
                                        &bullet;
                                        <span class="deep-orange-text"><?= _e(_money($order['price'])) ?></span>
                                        <nobr>&bullet;
                                            <span
                                                class="blue-grey-text text-lighten-2"><?= _e($order['created']) ?></span>
                                        </nobr>
                                    </span>

                                <?php else : ?>

                                    <span class="title">
                                        <span class="deep-orange-text"><?= _e(_money($order['price'])) ?></span>
                                        <nobr>&bullet;
                                            <span
                                                class="blue-grey-text text-lighten-2"><?= _e($order['created']) ?></span>
                                        </nobr>
                                    </span>

                                <?php endif; ?>

                                <p><?= _e($order['description']) ?></p>

                                <div class="secondary-content">
                                    <form data-form="execute-order"
                                          action="<?= _e(router_get_path('orders', 'execute')) ?>" method="post">
                                        <input type="hidden" name="id" value="<?= _e($order['id']) ?>">
                                        <button type="submit"
                                                class="btn-floating waves-effect waves-light transparent">
                                            <i class="material-icons mdi-action-done grey-text text-darken-4"
                                                title="Сделано!"></i></button>
                                    </form>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>

                <?php else : ?>

                    <p>Нет заказов. Зайдите позже.</p>

                <?php endif; ?>

            </div>
        </div>
    </div>
</main>

<?= template_render('_elements/footer'); ?>
</body>
</html>