<?php
?><!doctype html>
<html lang="ru">
<?= template_render('_elements/head', ['heading' => 'Список заказов']); ?>
<body>
<?= template_render('_elements/header'); ?>

<main>
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h2>Заказы</h2>

                <ul class="collection order-list">
                    <li class="collection-item avatar">
                        <img src="/static/img/stub/faust-falero.jpg" alt="Falero" class="circle">
                        <span class="title">Falero &bullet; <span class="deep-orange-text">43.89</span></span>

                        <p>Всевышний дух! ты всё, ты всё мне дал,
                            О чём тебя я умолял;
                            Недаром зрелся мне
                            Твой лик, сияющий в огне.
                            Ты дал природу мне, как царство, во владенье;
                            Ты дал душе моей
                            Дар чувствовать её, дал силу наслажденья.
                            Иной едва скользит по ней
                            Холодным взглядом удивленья;
                            Но я могу в её таинственную грудь,
                            Как в сердце друга, заглянуть.
                            Ты протянул передо мною
                            Созданий цепь — я узнаю
                            В водах, в лесах, под твердью голубою
                            Одну благую мать, одну её семью.
                        </p>

                        <div class="secondary-content">
                            <form action="">
                                <button type="submit" class="btn-floating waves-effect waves-light deep-orange"><i
                                        class="material-icons mdi-action-done" title="Сделано!"></i></button>
                            </form>
                        </div>
                    </li>
                    <li class="collection-item avatar">
                        <img src="/static/img/stub/faust-fragonard.jpg" alt="Fragonard" class="circle">
                        <span class="title">Fragonard &bullet; <span class="deep-orange-text">443.89</span></span>

                        <p>Всевышний дух! ты всё, ты всё мне дал,
                            О чём тебя я умолял;
                            Недаром зрелся мне
                            Твой лик, сияющий в огне.
                        </p>

                        <div class="secondary-content">
                            <form action="">
                                <button type="submit" class="btn-floating waves-effect waves-light deep-orange"><i
                                        class="material-icons mdi-action-done" title="Сделано!"></i></button>
                            </form>
                        </div>
                    </li>
                    <li class="collection-item avatar">
                        <img src="/static/img/stub/faust-falero.jpg" alt="Falero" class="circle">
                        <span class="title">Falero &bullet; <span class="deep-orange-text">108</span></span>

                        <p>Всевышний дух! ты всё, ты всё мне дал,
                            О чём тебя я умолял;
                            Недаром зрелся мне
                            Твой лик, сияющий в огне.
                            Ты дал природу мне, как царство, во владенье;
                            Ты дал душе моей
                            Дар чувствовать её, дал силу наслажденья.
                        </p>

                        <div class="secondary-content">
                            <form action="">
                                <button type="submit" class="btn-floating waves-effect waves-light deep-orange"><i
                                        class="material-icons mdi-action-done" title="Сделано!"></i></button>
                            </form>
                        </div>
                    </li>
                    <li class="collection-item avatar">
                        <img src="/static/img/stub/faust-retzsch.jpg" alt="Retzsch" class="circle">
                        <span class="title">Retzsch &bullet; <span class="deep-orange-text">43.93</span></span>

                        <p>Всевышний дух! ты всё, ты всё мне дал,
                            О чём тебя я умолял;
                            Недаром зрелся мне
                            Твой лик, сияющий в огне.
                            Ты дал природу мне, как царство, во владенье;
                            Ты дал душе моей
                            Дар чувствовать её, дал силу наслажденья.
                            Иной едва скользит по ней
                            Холодным взглядом удивленья;
                            Но я могу в её таинственную грудь,
                            Как в сердце друга, заглянуть.
                            Ты протянул передо мною
                            Созданий цепь — я узнаю
                            В водах, в лесах, под твердью голубою
                            Одну благую мать, одну её семью
                        </p>

                        <div class="secondary-content">
                            <form action="">
                                <button type="submit" class="btn-floating waves-effect waves-light deep-orange"><i
                                        class="material-icons mdi-action-done" title="Сделано!"></i></button>
                            </form>
                        </div>
                    </li>
                    <li class="collection-item avatar">
                        <img src="/static/img/stub/faust-vrubel.jpg" alt="Vrubel" class="circle">
                        <span class="title">Vrubel &bullet; <span class="deep-orange-text">2987</span></span>

                        <p>Всевышний дух! ты всё, ты всё мне дал,
                            О чём тебя я умолял.
                        </p>

                        <div class="secondary-content">
                            <form action="">
                                <button type="submit" class="btn-floating waves-effect waves-light deep-orange"><i
                                        class="material-icons mdi-action-done" title="Сделано!"></i></button>
                            </form>
                        </div>
                    </li>
                    <li class="collection-item avatar">
                        <img src="/static/img/stub/faust-vrubel.jpg" alt="Vrubel" class="circle">
                        <span class="title">Vrubel &bullet; <span class="deep-orange-text">102387443.89</span></span>

                        <p>Всевышний дух! ты всё, ты всё мне дал,
                            О чём тебя я умолял;
                            Недаром зрелся мне
                            Твой лик, сияющий в огне.
                        </p>

                        <div class="secondary-content">
                            <form action="">
                                <button type="submit" class="btn-floating waves-effect waves-light deep-orange"><i
                                        class="material-icons mdi-action-done" title="Сделано!"></i></button>
                            </form>
                        </div>
                    </li>
                    <li class="collection-item avatar">
                        <img src="/static/img/stub/faust-falero.jpg" alt="Falero" class="circle">
                        <span class="title">Falero &bullet; <span
                                class="deep-orange-text">1143243433434343.89</span></span>

                        <p>Всевышний дух! ты всё, ты всё мне дал,
                            О чём тебя я умолял;
                            Недаром зрелся мне
                            Твой лик, сияющий в огне.
                            Ты дал природу мне, как царство, во владенье;
                            Ты дал душе моей
                            Дар чувствовать её, дал силу наслажденья.
                        </p>

                        <div class="secondary-content">
                            <form action="">
                                <button type="submit" class="btn-floating waves-effect waves-light deep-orange"><i
                                        class="material-icons mdi-action-done" title="Сделано!"></i></button>
                            </form>
                        </div>
                    </li>
                    <li class="collection-item avatar">
                        <img src="/static/img/stub/faust-schlick.jpg" alt="Schlick" class="circle">
                        <span class="title">Schlick &bullet; <span class="deep-orange-text">403.89</span></span>

                        <p>Всевышний дух! ты всё, ты всё мне дал,
                            О чём тебя я умолял;
                            Недаром зрелся мне
                            Твой лик, сияющий в огне.
                            Ты дал природу мне, как царство, во владенье;
                            Ты дал душе моей
                            Дар чувствовать её, дал силу наслажденья.
                            Иной едва скользит по ней
                            Холодным взглядом удивленья;
                            Но я могу в её таинственную грудь,
                            Как в сердце друга, заглянуть.
                            Ты протянул передо мною
                            Созданий цепь — я узнаю
                            В водах, в лесах, под твердью голубою
                            Одну благую мать, одну её семью
                        </p>

                        <div class="secondary-content">
                            <form action="">
                                <button type="submit" class="btn-floating waves-effect waves-light deep-orange"><i
                                        class="material-icons mdi-action-done" title="Сделано!"></i></button>
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</main>

<?= template_render('_elements/footer'); ?>
</body>
</html>