<?php
/** @var array $orders */
/** @var array $customers */
/** @var string $next */
/** @var string $nextRand */
?><!doctype html>
<html lang="ru">
<?= template_render('_elements/head', ['heading' => 'Список заказов']); ?>
<body>
<?= template_render('_elements/header'); ?>

<main>
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h2>Заказы</h2>

                <ul class="collection order-list">
                    <?php if (!empty($orders)) : ?>
                        <?php foreach ($orders as $order) : ?>
                            <?php
                            $customer = isset($customers[$order['customer_id']]) ?
                                $customers[$order['customer_id']] :
                                false;
                            ?>
                            <li class="collection-item avatar order-item" id="order-item-<?= _e($order['id']) ?>">

                                <?php if (!empty($customer['avatar']) && isset($customer['username'])) : ?>
                                    <img src="<?= _e($customer['avatar']) ?>"
                                         alt="<?= _e($customer['username']) ?>"
                                         class="circle">

                                    <span class="title">
                                        <?= _e($customer['username']) ?>
                                        &bullet;
                                        <span class="deep-orange-text"><?= _e(_money($order['price'])) ?></span>
                                        <nobr>&bullet;
                                            <span
                                                class="blue-grey-text text-lighten-2"><?= _e($order['created']) ?></span>
                                        </nobr>
                                    </span>

                                <?php else : ?>

                                    <span class="title">
                                        <span class="deep-orange-text"><?= _e(_money($order['price'])) ?></span>
                                        <nobr>&bullet;
                                            <span
                                                class="blue-grey-text text-lighten-2"><?= _e($order['created']) ?></span>
                                        </nobr>
                                    </span>

                                <?php endif; ?>

                                <p><?= _e($order['description']) ?></p>

                                <div class="secondary-content">
                                    <form data-form="execute-order"
                                          action="<?= _e(router_get_path('orders', 'execute')) ?>" method="post">
                                        <input type="hidden" name="id" value="<?= _e($order['id']) ?>">
                                        <button type="submit"
                                                class="btn-floating waves-effect waves-light transparent">
                                            <i class="material-icons mdi-action-done grey-text text-darken-4"
                                               title="Сделано!"></i></button>
                                    </form>
                                </div>
                            </li>
                        <?php endforeach; ?>

                    <?php endif; ?>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col s12">
                <form action="<?= _e(router_get_path('orders', 'list')) ?>" method="get">
                    <input type="hidden" name="from" value="<?= _e($next) ?>">
                    <input type="hidden" name="fromRand" value="<?= _e($nextRand) ?>">

                    <div class="row">
                        <div class="input-field col s12">
                            <button type="submit"
                                    class="col s12 waves-effect waves-light btn deep-orange darken-4">
                                Показать ещё
                            </button>
                        </div>
                    </div>

                    <div class="row row-progress-bottom">
                        <div class="col s12 progress-container" data-progress="progress">
                            <div class="progress deep-orange lighten-4">
                                <div class="indeterminate deep-orange darken-4"></div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

<?= template_render('_elements/footer'); ?>
</body>
</html>